
// Generate random IDs
const generateId = () => Math.random().toString(36).substring(2, 10);

// Mock data for Clients tab
export const clientsData = [
  {
    id: generateId(),
    name: "Acme Corporation",
    contactPerson: "John Smith",
    rolesNeeded: 7,
    rolesHired: 3,
    requirementsCount: 12,
    totalRoles: 7,
    unassignedRoles: 2,
    tasAssigned: ["Sarah Johnson", "Mike Peters"],
    status: "Active",
    nextDueDate: "2025-06-15",
    priority: "High",
    lastActivity: "2025-05-20"
  },
  {
    id: generateId(),
    name: "Globex Industries",
    contactPerson: "Jane Doe",
    rolesNeeded: 5,
    rolesHired: 2,
    requirementsCount: 9,
    totalRoles: 5,
    unassignedRoles: 1,
    tasAssigned: ["Sarah Johnson"],
    status: "Active",
    nextDueDate: "2025-06-10",
    priority: "Medium",
    lastActivity: "2025-05-18"
  },
  {
    id: generateId(),
    name: "Initech LLC",
    contactPerson: "Michael Bolton",
    rolesNeeded: 3,
    rolesHired: 3,
    requirementsCount: 5,
    totalRoles: 3,
    unassignedRoles: 0,
    tasAssigned: ["Mike Peters", "David Kim"],
    status: "Active",
    nextDueDate: "2025-06-01",
    priority: "Low",
    lastActivity: "2025-05-21"
  },
  {
    id: generateId(),
    name: "Stark Industries",
    contactPerson: "Pepper Potts",
    rolesNeeded: 10,
    rolesHired: 4,
    requirementsCount: 18,
    totalRoles: 10,
    unassignedRoles: 3,
    tasAssigned: ["Sarah Johnson", "Mike Peters", "Lisa Wang"],
    status: "Active",
    nextDueDate: "2025-05-25",
    priority: "High",
    lastActivity: "2025-05-22"
  },
  {
    id: generateId(),
    name: "Wayne Enterprises",
    contactPerson: "Lucius Fox",
    rolesNeeded: 6,
    rolesHired: 1,
    requirementsCount: 11,
    totalRoles: 6,
    unassignedRoles: 2,
    tasAssigned: ["Lisa Wang", "David Kim"],
    status: "Active",
    nextDueDate: "2025-06-20",
    priority: "Medium",
    lastActivity: "2025-05-19"
  },
  {
    id: generateId(),
    name: "Umbrella Corporation",
    contactPerson: "Albert Wesker",
    rolesNeeded: 4,
    rolesHired: 0,
    requirementsCount: 8,
    totalRoles: 4,
    unassignedRoles: 4,
    tasAssigned: [],
    status: "Inactive",
    nextDueDate: "2025-07-01",
    priority: "Low",
    lastActivity: "2025-05-10"
  }
];

// Mock data for Roles tab
export const rolesData = [
  {
    id: generateId(),
    name: "Senior Software Engineer",
    clientName: "Acme Corporation",
    dueDate: "2025-06-15",
    budget: 150000,
    vacanciesFilled: 2,
    vacanciesOpen: 3,
    isActive: true,
    visibleExternally: true,
    stageConfiguredPercent: 100,
    taAssigned: ["Sarah Johnson", "Mike Peters"],
    timeInStage: 5,
    candidatesProgressed: 8,
    candidatesTotal: 10,
    interviewRatio: 60,
    openActions: 0,
    alerts: 1
  },
  {
    id: generateId(),
    name: "Product Manager",
    clientName: "Globex Industries",
    dueDate: "2025-06-10",
    budget: 120000,
    vacanciesFilled: 1,
    vacanciesOpen: 1,
    isActive: true,
    visibleExternally: true,
    stageConfiguredPercent: 85,
    taAssigned: ["Sarah Johnson"],
    timeInStage: 7,
    candidatesProgressed: 4,
    candidatesTotal: 12,
    interviewRatio: 33,
    openActions: 2,
    alerts: 0
  },
  {
    id: generateId(),
    name: "Full Stack Developer",
    clientName: "Initech LLC",
    dueDate: "2025-06-01",
    budget: 110000,
    vacanciesFilled: 3,
    vacanciesOpen: 0,
    isActive: true,
    visibleExternally: true,
    stageConfiguredPercent: 100,
    taAssigned: ["Mike Peters", "David Kim"],
    timeInStage: 0,
    candidatesProgressed: 16,
    candidatesTotal: 20,
    interviewRatio: 75,
    openActions: 0,
    alerts: 0
  },
  {
    id: generateId(),
    name: "AI Research Scientist",
    clientName: "Stark Industries",
    dueDate: "2025-05-25",
    budget: 180000,
    vacanciesFilled: 1,
    vacanciesOpen: 2,
    isActive: true,
    visibleExternally: true,
    stageConfiguredPercent: 100,
    taAssigned: ["Sarah Johnson", "Lisa Wang"],
    timeInStage: 21,
    candidatesProgressed: 2,
    candidatesTotal: 5,
    interviewRatio: 40,
    openActions: 1,
    alerts: 2
  },
  {
    id: generateId(),
    name: "Security Analyst",
    clientName: "Wayne Enterprises",
    dueDate: "2025-06-20",
    budget: 95000,
    vacanciesFilled: 0,
    vacanciesOpen: 2,
    isActive: true,
    visibleExternally: false,
    stageConfiguredPercent: 40,
    taAssigned: ["Lisa Wang"],
    timeInStage: 3,
    candidatesProgressed: 0,
    candidatesTotal: 0,
    interviewRatio: 0,
    openActions: 3,
    alerts: 1
  },
  {
    id: generateId(),
    name: "Biotech Researcher",
    clientName: "Umbrella Corporation",
    dueDate: "2025-07-01",
    budget: 130000,
    vacanciesFilled: 0,
    vacanciesOpen: 2,
    isActive: false,
    visibleExternally: false,
    stageConfiguredPercent: 20,
    taAssigned: [],
    timeInStage: 0,
    candidatesProgressed: 0,
    candidatesTotal: 0,
    interviewRatio: 0,
    openActions: 1,
    alerts: 0
  }
];

// Mock data for Requirements tab
export const requirementsData = [
  {
    id: generateId(),
    name: "React Native Expertise",
    linkedRole: "Senior Software Engineer",
    clientName: "Acme Corporation",
    taAssigned: ["Sarah Johnson"],
    status: "Open",
    priority: "High",
    dueDate: "2025-06-10",
    candidatesSourced: 8,
    interviewRatio: 62,
    candidateStageProgress: 65,
    modifiedPipeline: true
  },
  {
    id: generateId(),
    name: "Cloud Architecture Experience",
    linkedRole: "Senior Software Engineer",
    clientName: "Acme Corporation",
    taAssigned: ["Mike Peters"],
    status: "Open",
    priority: "Medium",
    dueDate: "2025-06-12",
    candidatesSourced: 5,
    interviewRatio: 40,
    candidateStageProgress: 35,
    modifiedPipeline: false
  },
  {
    id: generateId(),
    name: "Product Roadmap Development",
    linkedRole: "Product Manager",
    clientName: "Globex Industries",
    taAssigned: ["Sarah Johnson"],
    status: "Open",
    priority: "Medium",
    dueDate: "2025-06-05",
    candidatesSourced: 6,
    interviewRatio: 33,
    candidateStageProgress: 50,
    modifiedPipeline: false
  },
  {
    id: generateId(),
    name: "Node.js Backend Experience",
    linkedRole: "Full Stack Developer",
    clientName: "Initech LLC",
    taAssigned: ["Mike Peters"],
    status: "Closed",
    priority: "Low",
    dueDate: "2025-05-28",
    candidatesSourced: 12,
    interviewRatio: 75,
    candidateStageProgress: 100,
    modifiedPipeline: false
  },
  {
    id: generateId(),
    name: "Machine Learning Expertise",
    linkedRole: "AI Research Scientist",
    clientName: "Stark Industries",
    taAssigned: ["Sarah Johnson", "Lisa Wang"],
    status: "Open",
    priority: "High",
    dueDate: "2025-05-23",
    candidatesSourced: 3,
    interviewRatio: 33,
    candidateStageProgress: 25,
    modifiedPipeline: true
  },
  {
    id: generateId(),
    name: "Cybersecurity Certification",
    linkedRole: "Security Analyst",
    clientName: "Wayne Enterprises",
    taAssigned: ["Lisa Wang"],
    status: "Pending Approval",
    priority: "Medium",
    dueDate: "2025-06-18",
    candidatesSourced: 0,
    interviewRatio: 0,
    candidateStageProgress: 10,
    modifiedPipeline: false
  },
  {
    id: generateId(),
    name: "Biotechnology Research Experience",
    linkedRole: "Biotech Researcher",
    clientName: "Umbrella Corporation",
    taAssigned: [],
    status: "Pending Approval",
    priority: "Low",
    dueDate: "2025-06-25",
    candidatesSourced: 0,
    interviewRatio: 0,
    candidateStageProgress: 0,
    modifiedPipeline: false
  }
];

// Mock data for TAs tab
export const tasData = [
  {
    id: generateId(),
    name: "Sarah Johnson",
    requirementsAssigned: 4,
    rolesManaged: 3,
    candidatesSourced: 18,
    outreachActivities: 47,
    conversionRate: 38,
    averageSourcingTime: 5,
    workloadStatus: "Balanced",
    email: "sarah.j@company.com",
    phone: "+1-555-123-4567"
  },
  {
    id: generateId(),
    name: "Mike Peters",
    requirementsAssigned: 3,
    rolesManaged: 3,
    candidatesSourced: 25,
    outreachActivities: 62,
    conversionRate: 45,
    averageSourcingTime: 4,
    workloadStatus: "Balanced",
    email: "mike.p@company.com",
    phone: "+1-555-234-5678"
  },
  {
    id: generateId(),
    name: "Lisa Wang",
    requirementsAssigned: 3,
    rolesManaged: 2,
    candidatesSourced: 10,
    outreachActivities: 35,
    conversionRate: 30,
    averageSourcingTime: 7,
    workloadStatus: "Underloaded",
    email: "lisa.w@company.com",
    phone: "+1-555-345-6789"
  },
  {
    id: generateId(),
    name: "David Kim",
    requirementsAssigned: 2,
    rolesManaged: 2,
    candidatesSourced: 30,
    outreachActivities: 76,
    conversionRate: 52,
    averageSourcingTime: 3,
    workloadStatus: "Overloaded",
    email: "david.k@company.com",
    phone: "+1-555-456-7890"
  }
];
