// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irfigxdzqkphgeqykvyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyZmlneGR6cWtwaGdlcXlrdnlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzA4NzYsImV4cCI6MjA2MjgwNjg3Nn0.5NNvJJ2pjtSnXycJzOBVM-VnLR3Fg965WIgT5LMlcaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);